

//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import utility.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class HelpVarVisitor extends GJNoArguDepthFirst<Pair<String, ExpType>> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public Pair<String, ExpType> visit(VarDeclaration n) {
      Pair<String, ExpType> p1 = n.f0.accept(this);
      Pair<String, ExpType> p2 = n.f1.accept(this);
      return new Pair(p2.x, p1.y);
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public Pair<String, ExpType> visit(Type n) {
      return n.f0.accept(this);
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public Pair<String, ExpType> visit(ArrayType n) {
      ExpType t = new ExpType(ExpType.Type.INTARR);
      return new Pair<String, ExpType>("", t);
   }

   /**
    * f0 -> "boolean"
    */
   public Pair<String, ExpType> visit(BooleanType n) {
      ExpType t = new ExpType(ExpType.Type.BOOLEAN);
      return new Pair<String, ExpType>("", t);
   }

   /**
    * f0 -> "int"
    */
   public Pair<String, ExpType> visit(IntegerType n) {
      ExpType t = new ExpType(ExpType.Type.INT);
      return new Pair<String, ExpType>("", t);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
  public Pair<String, ExpType> visit(Identifier n) {
      if (!ClassTypes.isAClass(n.f0.toString())) {
        System.out.println("Type Error");
        System.exit(1);
      }

      ExpType t = new ExpType(ExpType.Type.ID, n.f0.toString());
      return new Pair<String, ExpType>("", t);
   }
}
