

//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;
import utility.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class LocalVarVisitor extends GJNoArguDepthFirst<Vector<Pair<String, ExpType>>> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public Vector<Pair<String, ExpType>> visit(NodeListOptional n) {
   	Vector<Pair<String, ExpType>> locals = new Vector<Pair<String, ExpType>>();
  	ShallowVarVisitor svvis = new ShallowVarVisitor();
    if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            locals.add(e.nextElement().accept(svvis));
         }
      }
         
    return locals;
   }
}
